{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ipapps.fluttermodule",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 16841505,
          "sha512": "a68d3e6ed18a7665c5a0e2e19f55f3521daf156d0c16b66496193438be8ea9e1b977afb90e41c82cd02f0f95d7e905c8c65b4b89102b6d8cdb2bb127cb6f9706",
          "sha256": "526b80bd35237c3864e9e07745db43239f3659f129b9e5e52782f6f7dde2a418",
          "sha1": "7f38b891226c600170d903b9bb26a3f0e2bcb13f",
          "md5": "ec75ab7a85c80b5a0f95c5f78e8822c1"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 16841505,
          "sha512": "a68d3e6ed18a7665c5a0e2e19f55f3521daf156d0c16b66496193438be8ea9e1b977afb90e41c82cd02f0f95d7e905c8c65b4b89102b6d8cdb2bb127cb6f9706",
          "sha256": "526b80bd35237c3864e9e07745db43239f3659f129b9e5e52782f6f7dde2a418",
          "sha1": "7f38b891226c600170d903b9bb26a3f0e2bcb13f",
          "md5": "ec75ab7a85c80b5a0f95c5f78e8822c1"
        }
      ]
    }
  ]
}
