{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.0.aar",
          "url": "share_plus_profile-1.0.aar",
          "size": 22322,
          "sha512": "b44378a4df09928445a39a850e62145c6a32f59c567dcd762226db9b29a7f21b12d27a16299de0c64b8bd58da0370b552a3f3aeb6b632e59606c06693c38630f",
          "sha256": "114fc84d1cbb845c01657b39d5d10e2545090fa03e1670422656857a07645585",
          "sha1": "43720c215d99eb44ad99b4b807e9fe8869cfefe1",
          "md5": "b89650bb0597f113084063cebe8532f3"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.0.aar",
          "url": "share_plus_profile-1.0.aar",
          "size": 22322,
          "sha512": "b44378a4df09928445a39a850e62145c6a32f59c567dcd762226db9b29a7f21b12d27a16299de0c64b8bd58da0370b552a3f3aeb6b632e59606c06693c38630f",
          "sha256": "114fc84d1cbb845c01657b39d5d10e2545090fa03e1670422656857a07645585",
          "sha1": "43720c215d99eb44ad99b4b807e9fe8869cfefe1",
          "md5": "b89650bb0597f113084063cebe8532f3"
        }
      ]
    }
  ]
}
